# Generated by Django 5.0.6 on 2024-06-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("due_date", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LongTermGoal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("target_date", models.DateTimeField()),
                ("progress", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=255)),
                ("completed", models.BooleanField(default=False)),
                ("time", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=6,
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("type", models.CharField(max_length=100)),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClassifyTask",
            fields=[
                (
                    "basetask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="App.basetask",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
            ],
            bases=("App.basetask",),
        ),
        migrations.CreateModel(
            name="TaskCompletion",
            fields=[
                (
                    "basetask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="App.basetask",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
            ],
            bases=("App.basetask",),
        ),
    ]
