# Generated by Django 5.0.6 on 2024-06-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
