import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer, Navbar } from "./components";
import { GoogleTagManager } from "@next/third-parties/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen">
          {" "}
          {/* Flex container for the entire layout */}
          {/* Fixed left-side navbar */}
          <div className="w-64 h-full fixed bg-blue-500 text-white flex flex-col p-4">
            {" "}
            {/* Fixed-width sidebar */}
            <Navbar /> The Navbar component with your sidebar navigation
          </div>
          {/* Main content area */}
          <div className="flex-1 ml-64">
            {" "}
            {/* Ensures space on the left and proper margin */}
            {children} {/* This is where the page-specific content will go */}
          </div>
        </div>
      </body>
      {/* Google Analytics or other scripts can go here */}
    </html>
  );
}
