import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer, Navbar } from "./components";
import { GoogleTagManager } from "@next/third-parties/google";

import "./globals.css";
import { Provider } from "./hooks/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <div className="flex min-h-screen">
            {" "}
            {/* Flex container for the entire layout */}
            {/* Fixed left-side navbar */} {/* Fixed-width sidebar */}
            <Navbar />
            {/* Main content area */}
            {/* ml64 need to change */}
            <div className="ml-32 flex-1">
              {" "}
              {/* Ensures space on the left and proper margin */}
              {children} {/* This is where the page-specific content will go */}
            </div>
          </div>
        </body>
      </Provider>
      {/* Google Analytics or other scripts can go here */}
    </html>
  );
}
