import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer, Navbar } from "./components";
import { GoogleTagManager } from "@next/third-parties/google";

import "./globals.css";
import { Provider } from "./hooks/provider";
import AvatarWidget from "./components/AvatarWidget";
import { getTaskStatus } from "./api/config";

const inter = Inter({ subsets: ["latin"] });

function getData() {
  return getTaskStatus();
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const taskStatus = await getData();

  return (
    <html lang="en">
      <Provider taskStatus={taskStatus}>
        <body className={inter.className}>
          {/* color bg-gray-50 */}
          <div className="flex min-h-screen bg-gray-50">
            {/* Fixed left-side navbar */} {/* Fixed-width sidebar */}
            <Navbar />
            {/* Main content area */}
            {/* ml64 need to change */}
            <div className="ml-32 flex-1">
              {" "}
              {/* Ensures space on the left and proper margin */}
              {children} {/* This is where the page-specific content will go */}
            </div>
            {/* AvatarWidget positioned absolutely in top left corner */}
            <div className="fixed top-10 right-10 z-50">
              <AvatarWidget
                name={"laihungwei"}
                title={"profile"}
                avatarUrl={
                  "https://lh3.googleusercontent.com/ogw/AF2bZyiiDW_pchr1lfLSiCs4oElU5zDtiXw7zOJqs2Ag17bRnIzz=s64-c-mo"
                }
              />
            </div>
          </div>
        </body>
      </Provider>
      {/* Google Analytics or other scripts can go here */}
    </html>
  );
}
