import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer, Navbar } from "./components";
import { GoogleTagManager } from "@next/third-parties/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed w-full top-0">
          <Navbar />
        </div>
        {/* custom the mt */}
        <div className="min-h-screen mt-[90px]">{children}</div>
        <Footer />
      </body>
      {/* ga */}
      {/* <GoogleTagManager gtmId="GTM-XYZ" /> */}
    </html>
  );
}
